# Generated by Django 2.0.3 on 2018-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_ticket', '0010_auto_20180410_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhaus_Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Fingerprint_device',
        ),
        migrations.DeleteModel(
            name='Mappingstation',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
